name: "Learning outcome frontend app CI"

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies and run tests
        run: |
          echo "Installing dependencies"
          npm install
          echo "Deploying app to heroku"
          npm run build
          echo "Running tests"
          npm test
